server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysqldb://localhost:3306/inbobwetrust?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qaz@WSX
mybatis:
  type-aliases-package: com.woojoolion.in-bob-we-trust
  mapper-locations: mapper/*.xml